# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vydU60UgOTLNYX36npAriIkINh7KcHKa
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,6])
y=np.array([0,250])
plt.plot(x,y)

x = [1, 1, 1,3,2,2,2, 3, 3]
y = [10,25,18,18,10,25,18, 25,10]
mycolor=['red','green', 'yellow', 'cyan', 'aqua', 'blue','black','orange','lime']
size=[50,100,150,200,250,300,350,400,450]
plt.scatter(x, y,color=mycolor, s=size)

x=np.array(["680-23", "682-23","681-23"])
y=np.array([65,5,3])
plt.bar(x,y,width=0.1)

x=np.array([1,2,3,4,5,6,7,8,9,10,11])
y=np.array([3,8,1,6,2,10,4,12,5,13,7])
plt.plot(x,y)

plt.plot(y,marker="h", ms=10,mfc="r")

x=np.array([2, 7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62])
plt.pie(x)

x=np.array([95,97,92,90,100])
mylabels=["SI","KA","EvS","KTE","MTvA"]
myexplode=[0.2,0.1,0.1,0.1,0.1]
plt.pie(x,labels=mylabels,startangle=90, explode=myexplode)

x=np.array([95,97,92,90,100])
mylabels=["SI","KTE","EvS","KA","MTvA"]
mycolor=['aqua', 'blue','red','orange','lime']
plt.pie(x,labels=mylabels, colors=mycolor)

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np
# Logotip yaratish
fig, ax = plt.subplots()

# Tashqi oq doira
outer_circle = patches.Circle((0.5, 0.5), 0.4, edgecolor="black", facecolor="white", lw=2)
ax.add_patch(outer_circle)

# Ichki oq doira
inner_circle = patches.Circle((0.5, 0.5), 0.3, edgecolor="black", facecolor="white", lw=2)
ax.add_patch(inner_circle)

# Ko'k va oq bo'limlar
blue_section_1 = patches.Wedge((0.5, 0.5), 0.3, 0, 90, facecolor="blue", edgecolor="black")
white_section_1 = patches.Wedge((0.5, 0.5), 0.3, 90, 180, facecolor="white", edgecolor="black")
blue_section_2 = patches.Wedge((0.5, 0.5), 0.3, 180, 270, facecolor="blue", edgecolor="black")
white_section_2 = patches.Wedge((0.5, 0.5), 0.3, 270, 360, facecolor="white", edgecolor="black")

ax.add_patch(blue_section_1)
ax.add_patch(white_section_1)
ax.add_patch(blue_section_2)
ax.add_patch(white_section_2)

# Harflarni joylashtirish (doira tashqi qismida)
ax.text(0.45, 0.85, "B", fontsize=14, color="black", ha="center", va="center")  # Tepada
ax.text(0.50, 0.85, "M", fontsize=14, color="black", ha="center", va="center")  # Chapda
ax.text(0.55, 0.85, "W", fontsize=14, color="black", ha="center", va="center")  # Pastda

# O'qni o'chirish va chizma nisbatini sozlash
ax.set_aspect('equal')
ax.axis('off')